name: 'Check mobile user-friendliness'
description: 'This action checks whether the website is user-friendly for a mobile device. The action uses Google's mobile friendly API (https://search.google.com/test/mobile-friendly). This requires an API key.'
inputs:
  site:  # id of input
    description: 'url of the site to check'
    required: true
    default: 'https://codedor.be'
  key:
    description: 'The Google API key'
    required: true
outputs:
  response: # id of output
    description: 'The response of the Google API'
runs:
  using: 'node12'
  main: 'index.js'