name: 'Check mobile user-friendliness'
description: 'This action checks whether the website is user-friendly for a mobile device.'
inputs:
  site:  # id of input
    description: 'url of the site to check'
    required: true
    default: 'https://codedor.be/'
  key:
    description: 'The Google API key'
    required: true
  image:
    description: 'Return Base64 to convert to an image'
    required: false
    default: false
outputs:
  response: # id of output
    description: 'The response of the Google API'
runs:
  using: 'node12'
  main: 'index.js'